version: '2'

services:

  db:
    image: postgres

  web:
    # Docker hack to wait until Postgres is up, then run stuff.
    command: bash -c "sleep 10; python /code/django_project/manage.py runserver 0.0.0.0:8000;"
    image: django
    # build: .
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      IN_DOCKER: 1

  webserver:
    image: jumanjiman/caddy
    depends_on:
      - web
    ports:
      - "80:8000"
    command: -port 8000 -host 0.0.0.0 "proxy / web:8000 { }"